# -*- coding: utf-8 -*-
"""COVID LI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NlS791e8Tw8W0tLn1bngP8Zs0-xtR-ld
"""

#This program shows the percentage of deaths by Co-Vid when contacting the disease as a NYC resident 
import pandas as pd # data analysis 
import matplotlib.pyplot as plt # plotting 
plt.style.use('fivethirtyeight') # style of charts / graphs

from google.colab import files 
files = files.upload() # import files

covid = pd.read_csv('COVID-19_Daily_Counts_of_Cases__Hospitalizations__and_Deaths.csv') # make the csv a dataframe 
covid = covid.set_index(pd.DatetimeIndex(covid['DATE_OF_INTEREST'].values)) # change 1st column to date time 
covid # print data

# print the mean, median, and standard deviation to find a measure of central tendencies 
print(covid['CASE_COUNT'].mean()) # find mean of cases in nyc residents 
print(covid['CASE_COUNT'].median()) # find the median of cases in nyc residents 
print(covid['CASE_COUNT'].std()) # find the standard deviation of cases in nyc residents

# visualize the case count - right skewed
plt.figure(figsize=(20,7)) # figure size 
plt.title('NYC Case Count ') # title 
plt.plot(covid['CASE_COUNT']) # plot covid case count
plt.xlabel('Date') # x label (horizontal)
plt.ylabel('Number of cases') # y label (vertical)
plt.show() # show graph

# visualize the death vs hosipitilized case count in NYC residents 
plt.figure(figsize=(20,7)) 
plt.title('NYC CO-VID Death vs Hospitlized Count ')
plt.plot(covid['HOSPITALIZED_COUNT'])
plt.plot(covid['DEATH_COUNT'])
plt.xlabel('Date')
plt.ylabel('Number of cases')
plt.show()

# find the death rate in covid cases as NYC residents 
death = covid['DEATH_COUNT'].sum() # find the total of deaths in NYC residents 
death # show total

total = covid['CASE_COUNT'].sum() # total case count in NYC residents
 total # show total

death_rate = round((death/total * 100), 3) # death rate in percentage rounded to thousandths 
print(str(death_rate) + "% of NYC residents' Co-vid 19 cases were deaths.") # print a statement showing the percentage of Covid cases deaths in NYC residents